### ISSUE TITLE
Poetry error `No module named 'toml'` after installing poetry-types 0.3.1

### ISSUE THREAD

**Issue by mikelane** [jvllmr/poetry-types#16]
I have installed Poetry v1.2.1 using the new standalone installer. Before I add poetry-types, I see that poetry runs successfully:

```shell
$ poetry --version
Poetry (version 1.2.1)
```

I then add the poetry-types plugin:

```shell
$ poetry self add poetry-types
```

I see the install happen with version 0.3.1 for poetry-types. Then I run poetry again and it fails:

```shell
$ poetry --version
No module named 'toml'
```

**Comment by mikelane** [comment]
Thanks for the update. I can now get poetry-types to install. But now I get this error:

```shell
$ poetry types update

module 'toml' has no attribute 'table'
```

**Comment by jvllmr** [comment]
Weird thing... I used the tomlkit API with the toml module and I did not notice ??? How did that ever work? Anyway, I fixed the issue and improved CI to hopefully catch a mistake like this in the future. Let me know if you run into any other issues.

**Comment by jvllmr** [comment]
I assume that it's fixed.
